spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/socialNetwork
    username: postgres
    password: 1006
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mail:
    host: localhost
    port: 1025
    username: hello@example.com
    password: hello
    protocol: smtp
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connection-timeout: 50000
        timeout: 3000
        write-timeout: 5000

  application:
    security:
      jwt:
        secret:
          access: BTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
          refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
